# Generated by Django 4.2.27 on 2026-01-18 04:31

import apps.messaging.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.messaging.models.UserManager()),
            ],
        ),
    ]
