# Generated by Django 4.2.27 on 2026-01-17 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Suspicious IP address', unique=True)),
                ('reason', models.TextField(help_text='Reason for flagging as suspicious')),
                ('flagged_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the IP was flagged')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Last time this IP was seen')),
                ('request_count', models.IntegerField(default=0, help_text='Number of requests in the detection window')),
            ],
            options={
                'verbose_name': 'Suspicious IP',
                'verbose_name_plural': 'Suspicious IPs',
                'ordering': ['-flagged_at'],
                'indexes': [models.Index(fields=['flagged_at'], name='security_su_flagged_09e0fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address to block', unique=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for blocking', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the IP was blocked')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who blocked this IP', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Client IP address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('path', models.CharField(help_text='Request path', max_length=500)),
                ('method', models.CharField(default='GET', help_text='HTTP method', max_length=10)),
                ('country', models.CharField(blank=True, help_text='Country from geolocation', max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text='City from geolocation', max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user if available', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='security_re_ip_addr_fb79d9_idx'), models.Index(fields=['timestamp'], name='security_re_timesta_c82a5d_idx'), models.Index(fields=['path'], name='security_re_path_5844a3_idx')],
            },
        ),
    ]
